<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_product_show' => [[], ['_controller' => 'App\\Controller\\CartController::showCart'], [], [['text', '/api/carts']], [], [], []],
    'app_product_add' => [['id'], ['_controller' => 'App\\Controller\\CartController::Add'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/carts']], [], [], []],
    'app_product_validate' => [[], ['_controller' => 'App\\Controller\\CartController::validate'], [], [['text', '/api/carts/validate']], [], [], []],
    'app_product' => [[], ['_controller' => 'App\\Controller\\ProductController::showAll'], [], [['text', '/api/products']], [], [], []],
    'project_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/api/products']], [], [], []],
    'product_show' => [['productId'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'productId', true], ['text', '/api/product']], [], [], []],
    'product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/product']], [], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/product']], [], [], []],
    'user_show' => [[], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/api/users']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/api/register']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login']], [], [], []],
];
